### ISSUE TITLE
Call cleanup function manually?

### ISSUE THREAD

**Issue by jingkaimori** [smack0007/deno-sdl2-ffi#10]
Typescript provide [FinalizationRegistry](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/eference/Global_Objects/FinalizationRegistry) for cleanup after corresponding object is deleted. Maybe we can call SDL cleanup functions like `SDL.DestroyWindow` in FinalizationRegistry.

**Comment by smack0007** [comment]
Sorry I'll have to reject this idea. One of my main goals in the library is:

```
Resembling the C API as much as possible. If someone reads a SDL tutorial (for example [LazyFoo](https://lazyfoo.net/tutorials/SDL/)) then they should be able to easily translate the tutorial to the equivalent in this library.
```

Once we start doing automatic cleanup and the like we start moving away from that goal.

For more context there already exists a different project that uses the Rust SDL bindings: https://github.com/littledivy/deno_sdl2
I find that this library is like it's own API. I can't read a tutorial about how to do something with SDL and directly imagine how to implement that in `deno_sdl2`.
