### ISSUE TITLE
Add SDL_WaitEvent

### ISSUE THREAD

**Issue by jingkaimori** [smack0007/deno-sdl2-ffi#7]
https://wiki.libsdl.org/SDL2/SDL_WaitEvent

Is it better to provide an async iterator for this API along with this blocking API? Or this api should be marked as [non-blocking](https://deno.land/manual@v1.35.0/runtime/ffi_api#non-blocking-ffi)?

**Comment by smack0007** [comment]
I honestly haven't thought about this. Will have to take a look at it when I get some time.

**Comment by jingkaimori** [comment]
Non-blocking ffi will blocking event loop, described in https://github.com/denoland/deno/pull/18436

**Comment by smack0007** [comment]
Implemented with https://github.com/smack0007/SDL_ts/pull/14

**Comment by jingkaimori** [comment]
`WaitEvent` should be defined as non-blocking function, but this feature has bug that prevent event loop to receive new events.

**Comment by smack0007** [comment]
I'm not sure that is a correct statement. The goal of the library is to reflect the C API as much as possible and as far as I can tell SDL_WaitEvent in C is definitely blocking. We could of course offer "SDL.WaitEventAsync" or something to that effect but we haven't implemented something like that anywhere else yet.
